[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "i686-linux-android",
  "x86_64-linux-android",
]
